#!/bin/sh

# Config Settings
bspc config split_ratio    0.5
bspc config border_width   2
bspc config window_gap     10
bspc config status_prefix  \>

bspc config normal_border_color     "#4c626d"
bspc config focused_border_color    "#93a1a1"
bspc config active_border_color     "#93a1a1"
bspc config presel_feedback_color   "#b58900"

bspc config click_to_focus      true
bspc config swallow_first_click true
bspc config pointer_modifier    control
bspc config pointer_action1     resize_corner
bspc config pointer_action2     resize_side
bspc config pointer_action3     move

bspc config honor_size_hints    true


# Rules
bspc rule --add Screenkey manage=off

# Setup desktops
bspc monitor --reset-desktops One Two Three Four Five

# Start panel.sh
#$HOME/.config/bspwm/panel.sh &
