#!/bin/sh

# Config Settings
bspc config split_ratio    0.5
bspc config border_width   2
bspc config window_gap     10
#bspc config top_padding   todo

bspc config auto_cancel    true
bspc config auto_alternate true

bspc config presel_border_color "#fdf6e3"
bspc config urgent_border_color "#ae5d5d"

bspc config focused_border_color "#93a1a1"
bspc config active_border_color  "#93a1a1"
bspc config normal_border_color  "#4c626d"

bspc config focused_locked_border_color "#484542"

# Rules
bspc rule --add Screenkey manage=off

# Setup desktops
bspc monitor --reset-desktops One Two Three Four Five
